version: '3.8'

# Development overrides for docker-compose.yml
# Usage: docker-compose -f docker-compose.yml -f docker-compose.dev.yml up

services:
  # Override user-auth-service for development
  user-auth-service:
    environment:
      - DEBUG=true
      - LOG_LEVEL=debug
      - JWT_SECRET_KEY=development-jwt-secret-key-not-for-production
    volumes:
      - ../UserAuthenticationMicroservice/src:/app/src:ro
      - user_auth_dev_data:/app/data

  # Add development database for user auth
  user-auth-db:
    image: postgres:15-alpine
    container_name: user-auth-postgres
    environment:
      - POSTGRES_DB=user_auth
      - POSTGRES_USER=user_auth_user
      - POSTGRES_PASSWORD=dev_password_123
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - microservices-network
    restart: unless-stopped

  # Development Redis for caching
  redis:
    image: redis:7-alpine
    container_name: redis-cache
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - microservices-network
    restart: unless-stopped
    command: redis-server --appendonly yes

  # Monitoring with Portainer (optional)
  portainer:
    image: portainer/portainer-ce:latest
    container_name: portainer
    ports:
      - "9000:9000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data
    networks:
      - microservices-network
    restart: unless-stopped

volumes:
  user_auth_dev_data:
    driver: local
  postgres_data:
    driver: local
  redis_data:
    driver: local
  portainer_data:
    driver: local